Repository googleapis/cloud-profiler-nodejs, pull requests merged in 2019-04, with the labels that each got.

#453 chore: redirect some test output to serial port 3
  testing/integration_test.go
Labels: cla: yes

#454 docs: mention building binaries and prebuilt binaries in docs
  README.md
Labels: cla: yes

#452 chore: add kokoro config for publishing with release tool
  .kokoro/release/publish.cfg
Labels: cla: yes

#456 v1.1.1
  package.json
Labels: cla: yes

#457 Release @google-cloud/profiler v1.1.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#458 chore: remove old kokoro configs and unused portions of tests
  system-test/integration_test.go
  system-test/integration_test.sh
  system-test/kokoro/continuous-v8-canary.cfg
  tools/kokoro/continuous/common.cfg
  tools/kokoro/continuous/continuous-v8-canary.cfg
  tools/kokoro/continuous/continuous.cfg
  tools/kokoro/presubmit/common.cfg
  tools/kokoro/presubmit/presubmit.cfg
  tools/kokoro/release/common.cfg
  tools/kokoro/release/linux.cfg
  tools/kokoro/release/publish-npm.cfg
  tools/publish.sh
Labels: cla: yes

#461 chore(dep): update mocha to 6.1
  package.json
Labels: cla: yes

#466 fix: update dependencies and tsconfig to support Node 6
  package.json
  system-test/busybench/tsconfig.json
  tsconfig.json
Labels: cla: yes

#468 fix: update dependencies for npm audit
  package.json
Labels: cla: yes

#472 build!: remove support for Node 6
  .circleci/config.yml
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
  system-test/integration_test.go
Labels: cla: yes

#473 update to .nycrc with --all enabled
  .nycrc
Labels: automerge, cla: yes, kokoro:run

#474 chore(deps): update dependency gts to v1
  package.json
  ts/src/config.ts
  ts/src/index.ts
  ts/src/logger.ts
  ts/src/profiler.ts
  ts/system-test/test-start.ts
  ts/test/profiles-for-tests.ts
  ts/test/test-init-config.ts
  ts/test/test-profiler.ts
Labels: cla: yes
