Repository googleapis/cloud-profiler-nodejs, pull requests merged in 2019-06, with the labels that each got.

#504 chore(deps): update sinon and @types/sinon
  package.json
Labels: cla: yes

#505 build: share some code for E2E tests
  system-test/integration_test.go
Labels: cla: yes

#506 chore: run gts fix
  ts/src/profiler.ts
  ts/test/test-profiler.ts
Labels: cla: yes

#502 build: use standard kokoro configuration
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .gitignore
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .prettierignore
  .prettierrc
  CODE_OF_CONDUCT.md
  codecov.yaml
  renovate.json
  synth.metadata
  synth.py
  ts/src/config.ts
  ts/src/index.ts
  ts/src/logger.ts
  ts/src/profiler.ts
  ts/system-test/test-start.ts
  ts/test/profiles-for-tests.ts
  ts/test/test-init-config.ts
  ts/test/test-profiler.ts
Labels: cla: yes

#508 build: set correct src path for template
  .jsdoc.js
  synth.metadata
  synth.py
Labels: cla: yes

#510 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#511 docs: add repo-metadata for docs
  .repo-metadata.json
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#513 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
Labels: cla: yes

#514 Release @google-cloud/profiler v2.0.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#517 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes

#509 feat(breaking!): support API endpoint override
  package.json
  ts/src/config.ts
  ts/src/index.ts
  ts/src/profiler.ts
  ts/test/test-init-config.ts
  ts/test/test-profiler.ts
Labels: :rotating_light:, cla: yes
