Repository googleapis/cloud-profiler-nodejs, pull requests merged in 2020-11, with the labels that each got.

#705 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: partial

#709 feat: add support for Node 14
  .github/workflows/ci.yaml
  system-test/integration_test.go
Labels: cla: yes

#712 docs: updated code of conduct
  .kokoro/trampoline_v2.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: cloudprofiler, cla: yes, context: full

#710 build: use standard CI config
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .github/workflows/ci2.yaml
  synth.py
Labels: api: cloudprofiler, cla: yes

#713 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudprofiler, automerge, cla: yes, context: full
