Repository googleapis/cloud-profiler-nodejs, pull requests merged in 2020-07, with the labels that each got.

#659 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#661 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#660 chore: fix code coverage reports
  .github/workflows/ci.yaml
Labels: cla: yes

#651 chore: add backoff integration test
  system-test/busybench/src/busybench.ts
  system-test/integration_test.go
  system-test/integration_test.sh
Labels: cla: yes

#666 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/docs.cfg
  .kokoro/presubmit/node8/lint.cfg
  .kokoro/presubmit/node8/samples-test.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#668 fix(deps): update dependency parse-duration to 0.4.4
  package.json
  src/config.ts
  src/profiler.ts
  test/test-profiler.ts
Labels: automerge, cla: yes

#674 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#675 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#676 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#678 chore: backoff test should run as a continuous, not presubmit, test
  system-test/integration_test.sh
Labels: cla: yes

#677 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#679 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#680 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#681 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
